# Generated by Django 5.1.5 on 2025-02-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_user_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='college_name',
            new_name='institute_name',
        ),
    ]
